version: "3.8"

services:
  mosquitto:
    container_name: MQTT_Broker
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - localnet
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  influxdb:
    container_name: Database
    image: influxdb:2.3.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    ports:
      - 8086:8086
    networks:
      - localnet
      
networks:
  localnet:
