version: "3.8"

services:
  mosquitto:
    container_name: MQTT_Broker
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - localnet
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      
networks:
  localnet:
