@startuml swarch

' title Contour


class "Contour" {
    x : int
    y : int
    width : int
    height : int
    markers : List[int]
}

' class "FoundObjectMaster" {
'     found_objects : list[FoundObject]
'     add_found_object(num: int, position: tuple[int, int, int, int], angle) -> None
'     get_best_match(point: tuple[int, int]) -> int
'     get_found_object(index: int) -> FoundObject
'     is_found_object(image, rectangle: tuple[int, int, int, int]) -> bool
'     reset()
'     update_found_object(a_list)
' }

@enduml