@startuml get_contours
title get_contours()

start
:Receive Image;
:Convert it to grayscale;
:Calculate the absolute difference between gray image and gray background;
:Add a gaussian blur to the result;
:Then calculate the binary threshold of the new result;
:Find the contours of the outcome;
:Return the contours;
stop

@enduml