@startuml premain
title Setup: Find which object should be tracked

participant Core
participant Helper
participant FoundObjectMaster

Core -> Helper : get_image()
Helper -> Core : image

Core -> Helper: get_contours()
Helper -> Core : contours

note right 
A contour represents a found object
end note

loop for contour in contours
    Core -> FoundObjectMaster : add_found_object()
end

note left 
The countours can also be filterd,
to remove static objects which should no be tracked
end note

@enduml