@startuml state
hide empty description

state .{
state Setup
state Tracking
state Settings
state Background

[*] --> Settings
Settings -> Background
Background -> Setup
Setup -> Tracking
Tracking -> Tracking
Tracking -> Background
}

. --> [*] : press q

@enduml