@startuml state
hide empty description

state .{
state Setup
state Tracking
state Settings
state Background

[*] --> Settings
Settings -> Background
Background -> Setup
Setup -> Tracking
Tracking -> Tracking : nothing pressed
Tracking -> Background : b pressed
}

. --> [*] : q pressed

@enduml