@startuml swarch
title Dependencies



class Scene
class Helper

class FoundObject
class FoundObjectMaster

class Drawer
class BackgroundManager
class PathGovernor

class VideoChef
class ImageGetter
class ObjectFinder
class Tracker
class HistogramStar

package States <<rectangle>>{
    abstract State
    class SetupState 
    class TrackingState
    
}

Scene -- FoundObjectMaster
Scene -- BackgroundManager

FoundObject -- Helper

FoundObjectMaster -- FoundObject
FoundObjectMaster -- HistogramStar

BackgroundManager -- PathGovernor

ImageGetter -- VideoChef

VideoChef -- PathGovernor

SetupState -- Tracker
SetupState -right- TrackingState
"State" <|-- SetupState

TrackingState -- Tracker
"State" <|-- TrackingState

Tracker -- Scene
Tracker -- ImageGetter
Tracker -- ObjectFinder
Tracker -- Drawer

HistogramStar -- PathGovernor

@enduml