@startuml swarch
title Dependencies



class Core
class Helper

class FoundObject
class FoundObjectMaster

class Drawer
class BackgroundManager
class PathGouverneur

class VideoChef
class ImageGetter
class ObjectFinder

Core -- FoundObject
Core -- FoundObjectMaster
Core -- Drawer
Core -- BackgroundManager
Core -- ImageGetter
Core -- ObjectFinder

Helper -- PathGouverneur

FoundObject -- Helper

FoundObjectMaster -- FoundObject
FoundObjectMaster -- Helper

BackgroundManager -- PathGouverneur

ImageGetter -- VideoChef

@enduml